package com.polus.fibicomp.constants;

public interface Constants {

	String MODULE_NAMESPACE_PROPOSAL_DEVELOPMENT = "KC-PD";
	String PARAMETER_COMPONENT_DOCUMENT = "Document";
	String ALL_SPONSOR_HIERARCHY_NIH_MULTI_PI = "ALL_SPONSOR_HIERARCHY_NIH_MULTI_PI";
	String KC_GENERIC_PARAMETER_NAMESPACE = "KC-GEN";
	String KC = "KC";
	String KC_ALL_PARAMETER_DETAIL_TYPE_CODE = "All";
	String SPONSOR_HIERARCHIES_PARM = "PERSON_ROLE_SPONSOR_HIERARCHIES";
	String NIH_MULTIPLE_PI_HIERARCHY = "NIH Multiple PI";
	String DEFAULT_SPONSOR_HIERARCHY_NAME = "DEFAULT";
	String INVALID_TIME = "Invalid Time";
}
